name: Norway, Small Map Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Verify TypeScript
        run: npm run lint

      - name: Format Code with Prettier
        run: npm run format

      - name: Build with Vite
        run: npm run build
